scale 2
skinparam Linetype ortho

skinparam class{
	  BackgroundColor<< MainProgramExecution>> Lime
}

title Class Diagram -- Tarea 1: CHAUCRAFT\nJavier Contreras (@contranton)\nIIC2233, 2018-1\n\nDiagram made with <i>plantuml</i>

class Universe{
      
      <get> Galaxy[] galaxies_list

      void _acquire_planets_and_galaxies()
      void write_content()
}

class Galaxy{
      str nombre
      
      <get> Planet[] planets_list
      <get/set> int minerales
      <get/set> int deuterio
}

Class Edificio #physical{
      int vida
      bool built
}

Class Cuartel #physical

Class Torre #physical{
      <get> int ataque
}

Edificio ^- Cuartel
Edificio ^- Torre

Class Planet{
      str nombre

      datetime ult_recoleccion

      <get/set> Raza raza

      bool conquistado
      <get/set> Torre torre
      <get/set> Cuartel cuartel

      int nivel_ataque = 0
      int nivel_economia = 0

      <get/set> int soldados 
      <get/set> int magos
      <get> int max_soldados
      <get> int max_magos
      
      <get> int effective_tasa_minerales
      <get> int tasa_minerales
      <get/set> int tasa_minerales
      <get/set> int tasa_deuterio
      
      <get> int evolucion
      
      <get> int ataque_efectivo
      <get> int vida_efectiva

      void maximize_stats()

}

Edificio --* Planet

Planet --* Galaxy
Galaxy --* Universe

abstract Class Raza<< Singleton >> #lightskyblue{

	 str nombre
	 bool has_mago
	 int max_pop

	 int[] costo_soldado
	 int[] rango_atq_soldado
	 int[] rango_vid_soldado

	 int[] costo_mago
	 int[] rango_atq_mago
	 int[] rango_vid_mago

	 str warcry

	 void habilidad(Entity entity1, Entity entity2)
}

 Class Maestro #powderblue

 Class Aprendiz #powderblue

 Class Asesino #powderblue

Maestro ..|> Raza
Aprendiz ..|> Raza
Asesino ..|> Raza

Raza --o Planet


' Menu system

abstract class Menu #lightcyan{
	 str title
	 str content
	 str prompt

	 {abstract} bool _validate_input()
	 bool _interact()

	 bool run()
}

 class NumericalChoiceMenu #lightcyan{
	 bool is_main

	 <get/set> items
	 <get> options
	 <get> functions
}

 class TextInputMenu #lightcyan

 class YesNoMenu #lightcyan

 class AreYouSureMenu #lightcyan

 class InfoMenu #lightcyan

 class NumericalInputMenu #lightcyan

Menu ^-- NumericalChoiceMenu
Menu ^-- TextInputMenu
Menu ^-- YesNoMenu
Menu ^-- InfoMenu
Menu ^-- NumericalInputMenu

YesNoMenu ^-- AreYouSureMenu

class MainMenu << MainProgramExecution >>{
      Universe universe

      bool create_galaxy()
      bool modify_galaxy()
      bool query_Galaxy()
      bool play_galaxy()
      bool quit_()
}

class CreateGalaxyMenu #gold{
      Universe universe

      Galaxy new_galaxy
      Planet[] new_planets
}

note left of MainMenu
     Different menus are created recursively through program execution. Detailed relationships
     concerning which main-like menus inherit which menu types have been obviated to
     avoid unnecessary clutter.
end note

class QueryGalaxyMenu #gold{
      Universe universe

      bool general_info()
      bool planet_info()
      bool best_galaxy()
      bool planet_ranking()
}

class ModifyGalaxyMenu #gold{
      Universe universe

      bool add_planet()
      bool eliminate_conquered()
      bool increase_mins_rate()
      bool increase_deut_rate()
      bool add_soldiers()
      bool add_wizards()
}

class PlayGalaxyMenu #gold{
      Universe universe
      Galaxy galaxy

      bool choose_galaxy()
      bool visit_planet()
      bool write_changes()
}

class VisitConqueredPlanetMenu #moccasin {

      void build_building()
      void create_units()
      void collect_resources()
      void make_improvements()
}

class VisitUnconqueredPlanetMenu #moccasin {
      
      void invade()
      void purchase()
}

class VisitPlanetMenu #moccasin{
      Planet planet

      bool event_archmage_invasion()
      bool event_asteroid_hit()
}

note bottom of VisitPlanetMenu
     Overwrites superclass's run() method to include random events
     end note

PlayGalaxyMenu *-- VisitPlanetMenu
VisitPlanetMenu ^-- VisitUnconqueredPlanetMenu
VisitPlanetMenu ^-- VisitConqueredPlanetMenu



Menu ^-- MainMenu
MainMenu *-- Menu

MainMenu --* Universe

' CreateGalaxyMenu --o Universe
' ModifyGalaxyMenu --o Universe
' QueryGalaxyMenu --o Universe
' PlayGalaxyMenu --o Universe

CreateGalaxyMenu --* MainMenu
ModifyGalaxyMenu --* MainMenu
QueryGalaxyMenu --* MainMenu
PlayGalaxyMenu --* MainMenu

note top of PlayGalaxyMenu
     This menu manages, <i>all by itself</i> the interactions concerning battles,
     the archmage, asteroids, etc, as these are not intrinsic parts of a planet
     or galaxy but rather actions performed <i><b>on</b></i> them
end note

Class Entity #snow{
      Galaxy galaxia
      str name
      Raza race
      Cuartel cuartel
      Torre torre
      
      int[] soldados
      int[] magos

      bool is_player
      bool being_invaded
      bool dup_attack

      str habilidad(Entity attacker, Entity defender)
      void generate_units(int n_soldados, int n_magos)

      <get> int ataque
      <get/set> int vida

      void duplicate_attack()
      void steal_minerals(int amount)

      void calculate_survivors()
}

Class Archimago #snow{
      <get/set> int vida
      str habilidad(Entity attacker, Entity defender)
}

Class Battle #snow{
      Entity attacker
      Entity defender
      Planet defender_planet

      int turn

      Generator battle_turns(Planet defender_planet)

      void make_entities(Galaxy galaxy, Planet|Archimago attacker, Planet defending_planet)
      void update_planets(Planet planet_attacker, Planet planet_defender)

      void _swap_attacker_defender()
      void _activate_abilities()
      str _generate_info(int attack, int original_life, int final_life)
}

Entity --* Battle
Archimago --^ Entity
Battle --* VisitPlanetMenu
